[tool.black]
line-length = 88
skip-string-normalization = true

[tool.poetry]
name = "ansible-waldur-module"
version = "1.1.2"
description = "Ansible module for the Waldur API."
authors = ["OpenNode Team <info@opennodecloud.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://waldur.com"
packages = [
    { include = "ansible_waldur_module", from = "src" }
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
ansible-core = ">=2.11.0"
python = ">=3.9,<4.0"
requests = ">=2.6.0"
python-waldur-client = ">=0.6.2"
urllib3 = "<2.0.0"
waldur-api-client = "0.2.0"

[tool.poetry.group.dev.dependencies]
responses = ">=0.5.0"
pre-commit = "^4.2.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.0"
mock = "^5.0"
respx = "^0.22.0"
httpx = "^0.28.1"
faker = "^37.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
